classifier:
  name: LDPNet
  kwargs:
    lamba1: 1.0
    lamba2: 0.15
    momentum: 0.998
    beta: 0.5
    query_aug_times: 1
    use_lr_classifier: True
    transductive: False
    transductive_iter: 7
    transductive_k: 10
    lr_max_iter: 1000
    local_query_crops: 0
